### ISSUE TITLE
Add `sbt-revolver` in the mix

### ISSUE THREAD

**Issue by zetashift** [http4s/http4s-io.g8#17]
How do we feel about adding https://github.com/spray/sbt-revolver to the giter8 template? I can add a PR if it's okay.

Advantages:
- Automatic reloading without any effort

Disadvantages:
- Yet another dependency to a template

It's not that much of an hassle to add `sbt-revolver` manually, but I think there is merit in having it included.

**Comment by rossabaker** [comment]
I haven't used it in a while, but we used to advertise it, and I always liked it.  I'm not sure why I got out of the habit.

**Comment by zetashift** [comment]
Dunno how I missed it, but sbt revolver is already available: https://github.com/http4s/http4s-io.g8/blob/0.23/src/main/g8/project/plugins.sbt#L2

The README doesn't mention it, so imo, would be cool to see the command `reStart` in there too. I can add a PR if wanted, but, does that mean I have to edit the README in all the relevant branches? (0.23/1.0, scala(3))
